var labels = {
	// common wikidata namespace
	"https://www.wikidata.org/wiki/Property:P31": "wd-prop:instance of",
	"https://www.wikidata.org/wiki/Property:P279": "wd-prop:subclass of",
	"https://www.wikidata.org/wiki/Property:P1629": "wd-prop:subject item of this property",
	"https://www.wikidata.org/wiki/Q18636219": "Wikidata property with datatype ‘time’",
	"https://www.wikidata.org/wiki/Property:P1646": "wd-prop:mandatory qualifier",
	"https://www.wikidata.org/wiki/Property:P585": "wd-prop:point in time",
	"https://www.wikidata.org/wiki/Q2245405": "key event",
	"https://www.wikidata.org/wiki/Property:P2302": "wd-prop:property constraint",
	"https://www.wikidata.org/wiki/Q21503250": "type constraint",
	"https://www.wikidata.org/wiki/Property:P2308":"wd-prop:class (qualifier)",
	"https://www.wikidata.org/wiki/Property:P2309":"wd-prop:relation (qualifier)",
	"https://www.wikidata.org/wiki/Q21503252":"instance of (type constr rel)",
	"https://www.wikidata.org/wiki/Property:P1687": "wd-prop:Wikidata property",
	// common rdf namespace
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "rdf:type",
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Property": "rdf:property",
	// common rdfs namespace
	"http://www.w3.org/2000/01/rdf-schema#label": "rdfs:label",
	"https://www.w3.org/2000/01/rdf-schema#domain": "rdfs:domain",
	"https://www.w3.org/2000/01/rdf-schema#range": "rdfs:range",
	"https://www.w3.org/2000/01/rdf-schema#subClassOf": "rdfs:subClassOf",
	"https://www.w3.org/2000/01/rdf-schema#subPropertyOf": "rdfs:subProperty",
	//common w3/owl namespace
	"http://www.w3.org/2002/07/owl#FunctionalProperty": "owl:FunctionalProperty",
	"https://www.w3.org/2002/07/owl#Thing": "owl:Thing",
	"http://www.w3.org/2002/07/owl#equivalentProperty": "owl:equivalentProperty",
	"http://www.w3.org/2001/XMLSchema#double": "xsd:double",
	//common foaf
	"http://xmlns.com/foaf/0.1/homepage": "foaf:homepage",
	// common freebase namespace
	// last token in original url is acceptable for now
	// common movies
	"http://dbpedia.org/resource/Homegrown_(film)": "dbr:Homegrown film",
	"http://rdf.freebase.com/ns/m.02r53vq": "fb:Homegrown film",
	"http://www.wikidata.org/entity/Q301083": "wd:Homegrown film",
	"http://data.linkedmdb.org/resource/film/17746": "Homegrown film",
	// common aviation
	"https://www.wikidata.org/wiki/Q667443": "wd:Hughes H-4 Hercules",
	"http://dbpedia.org/resource/Hughes_H-4_Hercules": "dbr:Hughes H-4 Hercules",
	"http://rdf.freebase.com/ns/m.0cvjtgn": "fb:Hughes H-4 Hercules",
	//first flight
	"http://rdf.freebase.com/ns/aviation.aircraft.first_flight":"fb:first flight",
	"http://rdf.freebase.com/ns/aviation.aircraft_model.maiden_flight":"fb:maiden flight",
	"http://dbpedia.org/property/firstFlight": "dbp:first flight",
	"1947-11-02(xsd:date)": "1947-11-02 (xsd:date)",
	"http:www.wikidata.org/wiki/Property:P606": "wd-prop:first flight",
	"2_November_1947": "2 November 1947",
	"https://www.wikidata.org/wiki/Q24041613": "Wikidata property for aircrafts",
	"https://www.wikidata.org/wiki/Q23069609": "Wikidata property related to air transport",
	"https://www.wikidata.org/wiki/Q1362364": "wd:maiden flight",
	"https://www.wikidata.org/wiki/Q15921555": "flight",
	"https://www.wikidata.org/wiki/Property:P1647":"wd-prop:subproperty of",
	"https://www.wikidata.org/wiki/Property:P793":"wd-prop:significant event",
	//coordinate location
	"https://www.wikidata.org/wiki/Property:P625": "wd-prop:coordinate location",
	"https://www.wikidata.org/wiki/Q18615777": "Wikidata property to indicate a location",
	"https://www.wikidata.org/wiki/Q22664": "geographic coordinate system",
	"https://www.wikidata.org/wiki/Property:P2667": "wd-prop:corresponding template",
	"https://www.wikidata.org/wiki/Q6294369": "Template: Coord",
	"https://www.wikidata.org/wiki/Q1153376":"flying boat",
	"45°12'13''N,123°8'41''W": "45°12'13''N, 123°8'41''W",
	"45.204_-123.145": "45.204, -123.145",
	"http://www.w3.org/2003/01/geo/wgs84_pos#geometry": "wgs84_pos# geometry",
	"POINT(-123.14499664307_45.203998565674)": "POINT( -123.14499664307_ 45.203998565674)",
	"http://www.w3.org/2003/01/geo/wgs84_pos#long": "wgs84_pos# long",
	//common sports
	"https://www.wikidata.org/wiki/Q10333": "wd:Valencia CF",
	"https://www.wikidata.org/wiki/Property:P115":"wd-prop:home venue",
	"https://www.wikidata.org/wiki/Q202762":"wd:Mestalla Stadium",
	"http://rdf.freebase.com/ns/m.080_y":"fb:Valencia CF",
	"http://dbpedia.org/resource/Valencia_CF": "dbr:Valencia CF",
	//stadium wikidata
	"https://www.wikidata.org/wiki/Q19829914":"wd:Wikidata property for places",
	"https://www.wikidata.org/wiki/Q22964372":"wd:Wikidata property related to sport orgs",
	"https://www.wikidata.org/wiki/Q483110":"wd:stadium",
	"https://www.wikidata.org/wiki/Q21818626":"Wikidata property related to sport",
	"https://www.wikidata.org/wiki/Q18608993":"Wikidata property for items about orgs",
	"https://www.wikidata.org/wiki/Q4438121":"sports organization",
	//stadium freebase
	"http://rdf.freebase.com/ns/sports.sports_team.arena_stadium": "fb:sports. sports_steam. arena_stadium",
	//stadium dbpedia
	"http://dbpedia.org/resource/Mestalla_Stadium": "dbr:Mestalla Stadium",
	"http://dbpedia.org/resource/Catalonia": "dbr:Catalonia",
	"http://dbpedia.org/resource/Valencia": "dbr:Valencia",
	"http://dbpedia.org/ontology/ground": "dbo:ground",
	"http://dbpedia.org/property/ground": "dbp:ground",
	"http://dbpedia.org/resource/Estadio_Mestalla": "dbr:Estadio _Mestalla",
	"http://dbpedia.org/ontology/wikiPageRedirects": "dbo:wikiPageREdirects",
	"http://dbpedia.org/ontology/wikiPageWikiLink": "dbo:wikiPageWikiLink",
	//locatedIn WikiData
	"https://www.wikidata.org/wiki/Property:P131": "wd-prop:Located in the administrative territorial entity",
	"https://www.wikidata.org/wiki/Q8818": "wd:Valencia",
	"https://www.wikidata.org/wiki/Property:P17": "wd-prop:country",
	"https://www.wikidata.org/wiki/Q29": "wd:Spain",
	//locatedIn dbpedia
	"http://dbpedia.org/property/location":"location",
	"Avenida_Suecia,_s/n_(en)": "Avenida_Suecia, s/n ,(en)",
	"http://dbpedia.org/resource/Valencia": "dbr:Valencia",
	"http://dbpedia.org/ontoloy/country":"dbo:country",
	"http://dbpedia.org/resource/Spain":"dbr:Spain",
	//locatedIn freebase
	"http://rdf.freebase.com/ns/location.location.containedby": "fb:location. location. containedby",
	//team owner wikidata
	"https://www.wikidata.org/wiki/Property:P127": "wd-prop:owned by",
	"https://www.wikidata.org/wiki/Q7175463": "wd:Peter Lim",
	"https://www.wikidata.org/wiki/Q16869121": "wd:proprietor",
	"https://www.wikidata.org/wiki/Property:P580": "wd-prop:start time",
	//team owner dbpedia
	"http://dbpedia.org/resource/Peter_Lim": "dbr:Peter Lim",
	"http://dbpedia.org/ontology/Agent": "dbo:Agent",
	"http://dbpedia.org/property/owner": "dbp:owner",
	"http://dbpedia.org/ontology/owner": "dbo:owner",
	//taxon wikidata
	"https://www.wikidata.org/wiki/Q47542": "wd:Castor a.k.a Beaver",
	"https://www.wikidata.org/wiki/Property:P105": "wd-prop:taxon rank",
	"https://www.wikidata.org/wiki/Q34740": "wd:genus",
	"https://www.wikidata.org/wiki/Property:P225": "wd-prop:taxon name",
	//taxon dbpedia
	"http://dbpedia.org/resource/Beaver": "dbr:Beaver",
	"http://dbpedia.org/property/genus": "dbp:genus",
	//parent_taxon wikidata
	"https://www.wikidata.org/wiki/Q261363": "wd:Castoridae",
	"https://www.wikidata.org/wiki/Property:P171": "wd-prop:parent_taxon",
	//parent_taxon dbpedia
	"http://dbpedia.org/property/familia": "dbp:familia",
	"http://dbpedia.org/ontology/family": "dbo:family",
	"http://dbpedia.org/resource/Castoridae": "dbr:Catoridae",
	//parent_body wikidata
	"https://www.wikidata.org/wiki/Q111": "wd:Mars",
	"https://www.wikidata.org/wiki/Property:P397": "wd-prop:Parent astronomical body",
	"https://www.wikidata.org/wiki/Q7243056": "wd:Primary body",
	"https://www.wikidata.org/wiki/Q525": "wd:Sun",
	//parent_body dbpedia
	"http://dbpedia.org/resource/Mars": "db:Mars",
	"http://rdf.freebase.com/ns/astronomy.orbital_relationship.orbits": "fb:astronomy. orbital_relationship. orbits",
	"http://rdf.freebase.com/ns/base.exoplanetology.exoplanet.parent_star": "fb:base. exoplanetology. exoplanet. parent_Star",
	"http://rdf.freebase.com/ns/base.satelites.natural_satellite.orbited_body": "fb:base.satelites natural_satellite. orbited_body",
	"http://dbpedia.org/resource/Sun": "dbr:Sun",
	//orbital_period wikidata
	"https://www.wikidata.org/wiki/Property:P2146": "wd-prop:Orbital period",
	"https://www.wikidata.org/wiki/Q37640": "wd:Orbital period",
	"https://www.wikidata.org/wiki/Property:P2047": "wd-prop:Duration",
	"https://www.wikidata.org/wiki/Q21886162": "wd:Duration",
	"https://www.wikidata.org/wiki/Q1790144": "wd:Unit of time",
	"https://www.wikidata.org/wiki/Property:P2876": "wd-prop:type of unit for this property",
	"https://www.wikidata.org/wiki/Property:P1382": "wd-prop:Coincident with",
	//orbital_period dbpedia
	"http://dbpedia.org/ontology/orbitalPeriod": "dbo:Orbital period",
	"http://dbpedia.org/ontology/Planet/orbitalPeriod": "dbo: Planet/orbital_period",
	"5.9354294400000006E7(xsd:double)": "5.93542944 00000006E7 (xsd:double)",
	"162501.12(xsd:double)": "162501.12 (xsd:double)",
	"668.5991(xsd:double)": "668.5991 (xsd:double)",
	"686.9710000000001(xsd:day)": "686.971 0000000001 (xsd:day)",
	"1.8808(xsd:day)": "1.8808 (xsd:day)",
	"0.007738415509259259(xsd:day)": "0.00773841 5509259259 (xsd:day)",
	//orbital_period freebase
	"http://rdf.freebase.com/ns/astronomy.orbital_relationship.orbital_period": "astronomy. orbital_relationship. orbital_period",
	//band member wikidata
	"https://www.wikidata.org/wiki/Q722232": "wd:Switchfoot",
	"https://www.wikidata.org/wiki/Property:P527": "wd-prop:has part",
	"https://www.wikidata.org/wiki/Q2023856": "wd:Jerome Fontamillas",
	//band member dbpedia
	"http://dbpedia.org/resource/Switchfoot": "dbr:Switchfoot",
	"http://dbpedia.org/ontology/bandMember": "dbo:bandMember",
	"http://dbpedia.org/resource/Jerome_Fontamillas": "dbr:Jerome Fontamillas",
	"http://dbpedia.org/ontology/Band": "dbo:Band",
	"http://dbpedia.org/ontology/Person": "dbo:Person",
	"http://dbpedia.org/property/currentMembers": "dbp:currentMembers",
	"*JonForeman*TimForeman*ChadButler*JeromeFontamillas*DrewShirley(en)": "*Jon Foreman * Tim Foreman * Chad Butler * Jerome Fontamillas * Drew Shirley (en)",
	//band member freebase
	"http://rdf.freebase.com/ns/m.0pr13": "fb:Switchfoot",
	//Movies Wikidata
	"https://www.wikidata.org/wiki/Q301083": "wd:Homegrown",
	"https://www.wikidata.org/wiki/Property:P57": "wd-prop:director",
	"https://www.wikidata.org/wiki/Q469233": "wd:Stephen Gyllenhaal",
	"https://www.wikidata.org/wiki/Q18618644": "wd:Wikidata Property for items about works",
	"https://www.wikidata.org/wiki/Property:P1568": "wd-prop:domain",
	"https://www.wikidata.org/wiki/Q386724": "wd:work",
	"https://www.wikidata.org/wiki/Q3455803": "wd:Director",
	"https://www.wikidata.org/wiki/Property:P161": "wd-prop:Cast member",
	"https://www.wikidata.org/wiki/Q202735": "wd:Billy Bob Thornton",
	"https://www.wikidata.org/wiki/Q22965162": "Wikidata property for items about films",
	"https://www.wikidata.org/wiki/Property:P2302": "wd-prop:property constraint",
	"https://www.wikidata.org/wiki/Q21503250": "wd:type constraint",
	"https://www.wikidata.org/wiki/Property:P2308": "wd-prop:class",
	"https://www.wikidata.org/wiki/Q11424": "wd:film",
	"https://www.wikidata.org/wiki/Property:P2309": "wd-prop:relation",
	"https://www.wikidata.org/wiki/Q21503252": "wd:instance of",
	"https://www.wikidata.org/wiki/Q33999": "wd:Actor",
	"98minute": "98 minute",
	"https://www.wikidata.org/wiki/Q18668171": "orderable Wikidata property",
	"https://www.wikidata.org/wiki/Q21077852": "Wikidata property for physical quantities",
	"https://www.wikidata.org/wiki/Property:P577": "wd-prop:publication date",
	"https://www.wikidata.org/wiki/Q1361758": "wd:date of publication",
	"https://www.wikidata.org/wiki/Property:P495": "wd-prop:country of origin",
	"https://www.wikidata.org/wiki/Q30": "wd:United States",
	"https://www.wikidata.org/wiki/Q6256": "wd:country",
	//Movies Freebase
	"http://rdf.freebase.com/ns/film.film.directed_by": "fb:film.film. directed_by",
	"http://rdf.freebase.com/ns/film.film.runtime": "fb:film. film.runtime",
	"http://rdf.freebase.com/ns/m.03ky_f1": "fb:m.03ky_f1",
	"http://rdf.freebase.com/ns/m.021_gc4": "fb:m.021_gc4",
	"http://rdf.freebase.com/ns/m.0glb1s4": "fb:m.0glb1s4",
	"http://rdf.freebase.com/ns/type.object.type": "fb:type. object.type",
	"http://rdf.freebase.com/ns/film.film_cut": "fb:film. film_cut",
	"http://rdf.freebase.com/ns/film.film_cut.film": "fb:film. film_cut.film",
	"http://rdf.freebase.com/ns/film.film_cut.runtime": "fb:film. film_cut.runtime",
	"http://rdf.freebase.com/ns/film.film.initial_release_date": "fb:filim.film. initial release date",
	"http://rdf.freebase.com/ns/film.film.release_date_s": "fb:Release date s",
	"http://rdf.freebase.com/ns/type.object.type": "fb:type. object.type",
	"http://rdf.freebase.com/ns/film.film_regional_release_date": "fb:film. film_regional _release_date",
	"http://rdf.freebase.com/ns/film.film_regional_release_date.release_date": "fb:film. film_regional _release_date. release_date",
	"http://rdf.freebase.com/ns/film.film_regional_release_date.film": "fb:film. film_regional _release_date .film",
	"http://rdf.freebase.com/ns/film.film_regional_release_date.film_release_distribution_medium": "fb:film.film _regional_release _date.film_release _distribution_medium",
	"http://rdf.freebase.com/ns/film.film.country": "fb:film. film.country",
	//Movies DBPedia
	"http://dbpedia.org/ontology/director": "dbo:director",
	"http://dbpedia.org/property/director": "dbp:director",
	"http://dbpedia.org/resource/Stephen_Gyllenhaal": "dbr:Stephen Gyllenhaal",
	"http://dbpedia.org/ontology/Person": "dbo:Person",
	"http://dbpedia.org/ontology/starring": "dbo:starring",
	"http://dbpedia.org/property/starring": "dbp:starring",
	"http://dbpedia.org/resource/Billy_Bob_Thornton": "dbr:Billy Bob Thornton",
	"http://dbpedia.org/ontology/Actor": "dbo:ACtor",
	"http://dbpedia.org/ontology/Work": "dbo:Work",
	"http://dbpedia.org/ontology/Work/runtime": "dbo:Work/runtime(m)",
	"http://dbpedia.org/ontology/runtime": "dbo:runtime(s)",
	"115.0^^http://dbpedia.org/datatype/minute": "115.0^^http:// dbpedia.org/ datatype/minute",
	"6900.0^^http://dbpedia.org/datatype/second": "6900.0^^http:// dbpedia.org/ datatype/second",
	"http://dbpedia.org/datatype/minute": "db:datatype/ minute",
	"http://dbpedia.org/ontology/releaseDate": "dbo:release date",
	"http://dbpedia.org/property/released": "dbp:released",
	"1998-04-17(xsd:date)": "1998-04-17 (xsd:date)",
	"http://dbpedia.org/resource/DVD": "dbr:DVD",
	"http://dbpedia.org/ontology/Country": "dbo:Country",
	"http://dbpedia.org/property/country": "dbr:country",
	"http://dbpedia.org/ontology/PopulatedPlace": "dbo:PopulatedPlace",
	"http://dbpedia.org/resource/United_States": "dbr:United States",
	//Movies LMDB
	"http://data.linkedmdb.org/resource/film/17746": "lmdb:Homegrown",
	"http://data.linkedmdb.org/page/film/17746": "lmdb:Homegrown",
	"http://data.linkedmdb.org/resource/movie/director": "lmdb:director",
	"http://data.linkedmdb.org/page/director/10534": "lmdb:Stephen Gyllenhaal",
	"http://data.linkedmdb.org/resource/movie/performance": "lmdb:performance",
	"http://data.linkedmdb.org/resource/actor/29395": "lmdb:Billy Bob Thornton",
	"http://data.linkedmdb.org/resource/movie/initial_release_date": "lmdb:initial release date",
	//Restaurant DBPedia
	"http://dbpedia.org/resource/In-N-Out_Burger": "dbr:In-N-Out_Burger",
	"http://dbpedia.org/ontology/keyPerson": "dbo:key person",
	"http://dbpedia.org/resource/Lynsi_Snyder": "dbr:Lynsi Snyder",
	"http://dbpedia.org/resource/Lynsi_Martinez": "dbr:Lynsi Martinez",
	"http://dbpedia.org/property/keyPeople [dbp:keyPeople]": "dbp:Key People",
	"http://purl.org/dc/elements/1.1/subject": "dc:subject",
	"http://dbpedia.org/resource/Category:Restaurants_established_in_1948": "dbr:Restaurants established in 1948",
	"http://dbpedia.org/ontology/locationCity": "dbo:location City",
	"http://dbpedia.org/property/locationCity": "dbp:location City",
	"http://dbpedia.org/resource/Irvine,_California": "dbr:Irvine California",
	"http://dbpedia.org/ontology/City": "dbo:City",
	"http://dbpedia.org/ontology/Organisation": "dbo:Organisation",
	"http://dbpedia.org/ontology/location": "dbo:location",
	"http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasLocation": "ontodesign: owl#hasLocation",
	"http://dbpedia.org/ontology/foundationPlace": "dbo:foundationPlace",
	"http://dbpedia.org/resource/Baldwin_Park,_California": "dbr:Baldwin_Park, California",
	"http://dbpedia.org/property/foundation": "dbp:foundation",
	"EstimatedUS$465million@en": "Estimated US $465 million @en",
	"http://dbpedia.org/property/revenue": "dbp:revenue",
	"http://dbpedia.org/ontology/revenue": "dbo:revenue",
	//Restaurant Freebase
	"http://rdf.freebase.com/ns/m.02bb8z": "fb:In-N-Out_Burger",
	"http://rdf.freebase.com/ns/common.topic.official_website":"fb:common.topic. official_website",
	"http://rdf.freebase.com/ns/common.topic.topical_webpage": "fb:common.topic. topical_webpage",
	"http://rdf.freebase.com/ns/common.topic.webpage":"fb:common. topic.webpage",
	"http://framebase.org/ns/dereif-Leadership-isLedByLeader": "framebase:dereif- Leadership- isLedByLeader",
	"http://rdf.freebase.com/ns/m.043s6dz": "fb:Lynsi Martinez",
	"http://www.ontotext.com/proton/protontop#establishmentDate": "ptop:establishment Date",
	"http://www.ontotext.com/proton/protontop#Organization": "ptop:Organizatioin",
	"http://rdf.freebase.com/ns/organization.organization.date_founded": "fb:organization. organization. date_founded",
	"http://www.ontotext.com/proton/protontop#locatedIn": "ptop:locatedIn",
	"Irvine,California,U.S.@en": "Irvine, California, U.S. @en",
	"http://rdf.freebase.com/ns/organization.organization.headquarters": "fb:organization. organization. headquarters",
	"http://rdf.freebase.com/ns/m.040s072": "fb:m.040s072",
	"http://www.ontotext.com/proton/protontop#Entity": "ptop:Entity",
	"http://www.ontotext.com/proton/protontop#Location": "ptop:Location",
	"http://www.ontotext.com/proton/protontop#establishedIn": "ptop:EstablishedIn",
	"http://rdf.freebase.com/ns/organization.organization.place_founded": "fb:organization. organization. place_founded",
	//Restaurant WikiData
	"https://www.wikidata.org/wiki/Q1205312": "wd:In-N-Out_Burger",
	"https://www.wikidata.org/wiki/Property:P856": "wd-prop: official website",
	"https://www.wikidata.org/wiki/Q18608871": "WikiData property for items about people",
	"https://www.wikidata.org/wiki/Property:P571": "wd-prop: Inception",
	"https://www.wikidata.org/wiki/Q18636219": "wd:Wikidata property with datatype 'time'",
	"https://www.wikidata.org/wiki/Property:P159": "wd-prop:Headquarter Location",
	"https://www.wikidata.org/wiki/Property:P276": "wd-prop:location",
	"https://www.wikidata.org/wiki/Q49219": "wd:Irvine",
	"https://www.wikidata.org/wiki/Q7540126": "wd:headquarters",
	"https://www.wikidata.org/wiki/Property:P740": "wd-prop:location of formation",
	"https://www.wikidata.org/wiki/Q804878": "wd:Baldwin Park",
	"https://www.wikidata.org/wiki/Q18635217": "Wikidata property for specifying the location of an event",
	//Restaurant Yago
	"http://yago-knowledge.org/resource/In-N-Out_Burger": "yago:In-N-Out_Burger",
	"http://framebase.org/ns/dereif-Creating-isCreatedAtTime": "frambase:dereif- Creating- isCreatedAtTime",
}